# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/scleaner
CFG_INC=-Isrc/engine -Isrc/interface -Isrc/leak -Isrc/log -Isrc/tools \
	-Isrc -I/usr/include/wx-2.8 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/engine.o $(OUTDIR)/settings_manager.o \
	$(OUTDIR)/checklistctrl.o $(OUTDIR)/maininterface.o \
	$(OUTDIR)/notif.o $(OUTDIR)/preferences.o \
	$(OUTDIR)/result_checklistctrl.o $(OUTDIR)/review.o \
	$(OUTDIR)/select_dialog.o $(OUTDIR)/systeminfos.o $(OUTDIR)/tray.o \
	$(OUTDIR)/memory_manager.o $(OUTDIR)/log.o $(OUTDIR)/checktreectrl.o \
	$(OUTDIR)/sclean.o $(OUTDIR)/tar.o $(OUTDIR)/TarConvert.o \
	$(OUTDIR)/testtar.o $(OUTDIR)/apt-cache.o \
	$(OUTDIR)/backupextensions.o $(OUTDIR)/coders.o $(OUTDIR)/coredump.o \
	$(OUTDIR)/emptyfolders.o $(OUTDIR)/iso.o $(OUTDIR)/kernels.o \
	$(OUTDIR)/latex.o $(OUTDIR)/logs.o $(OUTDIR)/mac.o \
	$(OUTDIR)/nullfiles.o $(OUTDIR)/orphan.o $(OUTDIR)/thumbnails.o \
	$(OUTDIR)/trash.o $(OUTDIR)/wma.o $(OUTDIR)/tbz.o \
	$(OUTDIR)/plugin_manager.o $(OUTDIR)/test_exception.o \
	$(OUTDIR)/test_thread.o $(OUTDIR)/thread.o $(OUTDIR)/mutex.o \
	$(OUTDIR)/name.o $(OUTDIR)/tar_archive.o $(OUTDIR)/testbz.o \
	$(OUTDIR)/thread.o $(OUTDIR)/timer.o $(OUTDIR)/scleaner_wx.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/engine.o $(OUTDIR)/settings_manager.o \
	$(OUTDIR)/checklistctrl.o $(OUTDIR)/maininterface.o \
	$(OUTDIR)/notif.o $(OUTDIR)/preferences.o \
	$(OUTDIR)/result_checklistctrl.o $(OUTDIR)/review.o \
	$(OUTDIR)/select_dialog.o $(OUTDIR)/systeminfos.o $(OUTDIR)/tray.o \
	$(OUTDIR)/memory_manager.o $(OUTDIR)/log.o $(OUTDIR)/checktreectrl.o \
	$(OUTDIR)/sclean.o $(OUTDIR)/tar.o $(OUTDIR)/TarConvert.o \
	$(OUTDIR)/testtar.o $(OUTDIR)/apt-cache.o \
	$(OUTDIR)/backupextensions.o $(OUTDIR)/coders.o $(OUTDIR)/coredump.o \
	$(OUTDIR)/emptyfolders.o $(OUTDIR)/iso.o $(OUTDIR)/kernels.o \
	$(OUTDIR)/latex.o $(OUTDIR)/logs.o $(OUTDIR)/mac.o \
	$(OUTDIR)/nullfiles.o $(OUTDIR)/orphan.o $(OUTDIR)/thumbnails.o \
	$(OUTDIR)/trash.o $(OUTDIR)/wma.o $(OUTDIR)/tbz.o \
	$(OUTDIR)/plugin_manager.o $(OUTDIR)/test_exception.o \
	$(OUTDIR)/test_thread.o $(OUTDIR)/thread.o $(OUTDIR)/mutex.o \
	$(OUTDIR)/name.o $(OUTDIR)/tar_archive.o $(OUTDIR)/testbz.o \
	$(OUTDIR)/thread.o $(OUTDIR)/timer.o $(OUTDIR)/scleaner_wx.o 

COMPILE=g++ -c    -g -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -g -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : src/test/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/morgue/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/apt-cache/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/backupextensions/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/tools/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/wma/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/nullfiles/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/mac/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/logs/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/out/tbz/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/trash/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/thumbnails/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/interface/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/log/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coredump/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coders/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/iso/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/orphan/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/latex/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/kernels/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/engine/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/leak/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/emptyfolders/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/test/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/morgue/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/apt-cache/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/backupextensions/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/tools/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/wma/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/nullfiles/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/mac/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/logs/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/out/tbz/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/trash/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/thumbnails/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/interface/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/log/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coredump/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coders/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/iso/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/orphan/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/latex/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/kernels/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/engine/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/leak/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/emptyfolders/%.c
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/scleaner
CFG_INC=-Isrc/engine -Isrc/interface -Isrc/leak -Isrc/log -Isrc/tools \
	-Isrc -I/usr/include/wx-2.8 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/engine.o $(OUTDIR)/settings_manager.o \
	$(OUTDIR)/checklistctrl.o $(OUTDIR)/maininterface.o \
	$(OUTDIR)/notif.o $(OUTDIR)/preferences.o \
	$(OUTDIR)/result_checklistctrl.o $(OUTDIR)/review.o \
	$(OUTDIR)/select_dialog.o $(OUTDIR)/systeminfos.o $(OUTDIR)/tray.o \
	$(OUTDIR)/memory_manager.o $(OUTDIR)/log.o $(OUTDIR)/checktreectrl.o \
	$(OUTDIR)/sclean.o $(OUTDIR)/tar.o $(OUTDIR)/TarConvert.o \
	$(OUTDIR)/testtar.o $(OUTDIR)/apt-cache.o \
	$(OUTDIR)/backupextensions.o $(OUTDIR)/coders.o $(OUTDIR)/coredump.o \
	$(OUTDIR)/emptyfolders.o $(OUTDIR)/iso.o $(OUTDIR)/kernels.o \
	$(OUTDIR)/latex.o $(OUTDIR)/logs.o $(OUTDIR)/mac.o \
	$(OUTDIR)/nullfiles.o $(OUTDIR)/orphan.o $(OUTDIR)/thumbnails.o \
	$(OUTDIR)/trash.o $(OUTDIR)/wma.o $(OUTDIR)/tbz.o \
	$(OUTDIR)/plugin_manager.o $(OUTDIR)/test_exception.o \
	$(OUTDIR)/test_thread.o $(OUTDIR)/thread.o $(OUTDIR)/mutex.o \
	$(OUTDIR)/name.o $(OUTDIR)/tar_archive.o $(OUTDIR)/testbz.o \
	$(OUTDIR)/thread.o $(OUTDIR)/timer.o $(OUTDIR)/scleaner_wx.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/engine.o $(OUTDIR)/settings_manager.o \
	$(OUTDIR)/checklistctrl.o $(OUTDIR)/maininterface.o \
	$(OUTDIR)/notif.o $(OUTDIR)/preferences.o \
	$(OUTDIR)/result_checklistctrl.o $(OUTDIR)/review.o \
	$(OUTDIR)/select_dialog.o $(OUTDIR)/systeminfos.o $(OUTDIR)/tray.o \
	$(OUTDIR)/memory_manager.o $(OUTDIR)/log.o $(OUTDIR)/checktreectrl.o \
	$(OUTDIR)/sclean.o $(OUTDIR)/tar.o $(OUTDIR)/TarConvert.o \
	$(OUTDIR)/testtar.o $(OUTDIR)/apt-cache.o \
	$(OUTDIR)/backupextensions.o $(OUTDIR)/coders.o $(OUTDIR)/coredump.o \
	$(OUTDIR)/emptyfolders.o $(OUTDIR)/iso.o $(OUTDIR)/kernels.o \
	$(OUTDIR)/latex.o $(OUTDIR)/logs.o $(OUTDIR)/mac.o \
	$(OUTDIR)/nullfiles.o $(OUTDIR)/orphan.o $(OUTDIR)/thumbnails.o \
	$(OUTDIR)/trash.o $(OUTDIR)/wma.o $(OUTDIR)/tbz.o \
	$(OUTDIR)/plugin_manager.o $(OUTDIR)/test_exception.o \
	$(OUTDIR)/test_thread.o $(OUTDIR)/thread.o $(OUTDIR)/mutex.o \
	$(OUTDIR)/name.o $(OUTDIR)/tar_archive.o $(OUTDIR)/testbz.o \
	$(OUTDIR)/thread.o $(OUTDIR)/timer.o $(OUTDIR)/scleaner_wx.o 

COMPILE=g++ -c   -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : src/test/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/morgue/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/apt-cache/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/backupextensions/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/tools/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/wma/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/nullfiles/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/mac/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/logs/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/out/tbz/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/trash/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/thumbnails/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/interface/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/log/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coredump/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coders/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/iso/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/orphan/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/latex/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/kernels/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/engine/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/leak/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/emptyfolders/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : src/test/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/morgue/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/apt-cache/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/backupextensions/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/tools/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/wma/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/nullfiles/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/mac/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/logs/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/out/tbz/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/trash/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/thumbnails/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/interface/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/log/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coredump/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/coders/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/iso/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/orphan/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/latex/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/kernels/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/engine/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/leak/%.c
	$(COMPILE)

$(OUTDIR)/%.o : src/plugins/in/emptyfolders/%.c
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
